#
# ElasticSearch Data Node Template.
# Creates volume and then server for data storage of ES.
#
heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running elasticsearch.

parameters:

  image:
    label: Server Image
    description: Operating system to use for your server.
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)

  availability_zone:
    label: AZ Selection
    description: Availability zone
    type: string
    default: SY2

  flavor:
    description: Flavor for Cloud Servers
    type: string
    default: 2 GB General Purpose v1

  server_hostname:
    description: Hostname for the server.
    type: string
    default: elasticsearch-%index%

  ssh_keypair_name:
    description: Nova keypair name for ssh access to the server
    type: string

#   es_network_id:
    # description: cloud network id for intra-cluster communication
    # type: string

  ssh_private_key:
    description: private key to access the created servers
    type: string

  es_password:
    description: password for HTTP basic auth
    type: string

  es_auth_user:
    description: User name for HTTP basic authentication to Elasticsearch endpoint
    type: string
    default: es_user

  es_version:
    description: Version of Elasticsearch to deploy
    type: string
    default: "1.4.3"

  stack_id:
    description: Stack ID
    type: string

resources:

  es_server:
    type: "OS::Nova::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: ssh_keypair_name }
      availability_zone: { get_param: availability_zone }
      metadata:
        rax-heat: { get_param: "stack_id" }
      #networks:
      #- network: { get_param: es_network_id }


outputs:
  #  es_server_ip:
  #  value: { get_attr: [es_server, accessIPv4] }

#  es_private_ip:
#    value: { get_attr: [es_server, networks, private, 0] }

